### ISSUE TITLE
试收一个组队的同学

### ISSUE THREAD

**Issue by ETCHKILI** [sqlab-sustech/CS323-2021F#1]

**Comment by dreamking60** [comment]
还收人吗？

**Comment by hotaru555** [comment]
收的
这是我的QQ 1500241540




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sqlab-sustech/CS323-2021F"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月11日(星期六) 晚上11:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [sqlab-sustech/CS323-2021F] 试收一个组队的同学 (#1)





 
还收人吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ETCHKILI** [comment]
还未收到，我QQ 1940824104
