### ISSUE TITLE
Providing tac parser cannot parse sample/test_4_fact.ir

### ISSUE THREAD

**Issue by bzy-debug** [sqlab-sustech/CS323-2021F#13]
When I use the providing tac parser to parse the sample/test_4_fact.ir, an assertion fails.
![image](https://user-images.githubusercontent.com/71200607/147666237-94f7153e-9435-4ed3-819b-36ee6c695e99.png)

**Comment by XDZhelheim** [comment]
We also found a bug in function [_str_split()](https://github.com/sqlab-sustech/CS323-2021F/blob/51321a274ef7aead5dd7339d4765351fc9da62b1/project4/tac.c#L31).
https://github.com/sqlab-sustech/CS323-2021F/blob/51321a274ef7aead5dd7339d4765351fc9da62b1/project4/tac.c#L31

In line 53, the fuction allocates memory for the array of string (`char** result`).
https://github.com/sqlab-sustech/CS323-2021F/blob/51321a274ef7aead5dd7339d4765351fc9da62b1/project4/tac.c#L53

In line 60 in the iteration, the value of each array element is set by `strdup()`, which calls `malloc()`.
https://github.com/sqlab-sustech/CS323-2021F/blob/51321a274ef7aead5dd7339d4765351fc9da62b1/project4/tac.c#L60

>The strdup() function returns a pointer to a new string which is a duplicate of the string s. Memory for the new string is obtained with malloc, and can be freed with free.

In line 63 and 64, if the assertion passes, which means `idx == count`, then `result + idx` is invalid memory access (array index out of bound), because it allocated only `count` length for the array.
https://github.com/sqlab-sustech/CS323-2021F/blob/51321a274ef7aead5dd7339d4765351fc9da62b1/project4/tac.c#L63-L64

**How we found this bug**

If the memory is allocated consecutively, line 64 `*(result + idx) = 0` will set the first string in the array to empty string.

However, it is hard to reproduce. We found it by accident because both of me and my teammate use m1 MBP. When `count == 2`, e.g. the input is `PARAM v0`, macOS (12.1 ARM64) will allocate memory consecutively. So the memory will be like:

`char** result | char* result[0] | char* result[1] | data0 | ...`

Then `result + idx == result + 2` is the address of `data0` (i.e. `result[0]`). So `*(result + idx) == *(result[0]) == result[0][0]`. Therefore, `*(result + idx) = 0` means `result[0][0] = 0`. Then `result[0]` will become an empty string because the first character is `\0`.

We reproduced this bug only on ARM macOS, and only when `count == 2` because macOS will allocate consecutively only when `count` is 2. Both Linux and Win10 cannot reproduce because they just won't allocate consecutively, but this invalid memory access may modify other variables' data in memory, which is harder to debug.

**Fix**

```c
result = malloc(sizeof(char*) * (count + 1)); 
```
or
```c
*(result + idx) = 0; // delete this line
```

**Comment by yepangliu** [comment]
@CirQ Can you take a look into the issues? Thanks.

**Comment by CirQ** [comment]
As you can see in the [source code](https://github.com/sqlab-sustech/CS323-2021F/blob/main/project4/tac.c#L32) that `_str_split` is copied&pasted from a stackoverflow [post](https://stackoverflow.com/questions/9210528/split-string-with-delimiters-in-c). But I have no idea why the assertion in the original answer becomes `assert(idx == count - 1)` which is totally different to that in `tac.c`. You may try to modify this assertion and see if it works (sorry for my local environment broken thus I cannot test it).

@XDZhelheim You may also try to modify the assertion to see if the bug still exists. If it does not help, the first patch (allocating one more pointer space) seems to be a nice choice and please send me a pull request.

Very thanks for reporting this issue!

**Comment by XDZhelheim** [comment]
Thanks for your suggestion.

If modify the assertion to `assert(idx == count - 1)`, it will always fail on my computer.

I will open a PR.
